---
name: Net-Flickr-Backup
version: 2.1
author:
  - Aaron Straup Cope E<lt>ascope@cpan.orgE<gt>
abstract: OOP for backing up your Flickr photos locally
license: perl
requires:
  Date::Format: >= 2.22
  Date::Parse: >= 2.27
  Encode: >= 2.09
  File::Find::Rule: 0
  IO::AtomicFile: >= 2.101
  LWP::Simple: >= 1.38
  Memoize: 0
  Net::Flickr::RDF: >= 1.1
  Sys::Hostname::FQDN: 0
  perl: >= 5.8.0
build_requires:
  Test::Simple: >= 0.47
provides:
  Net::Flickr::Backup:
    file: lib/Net/Flickr/Backup.pm
    version: 2.1
generated_by: Module::Build version 0.2611
