---
name: Net-Flickr-Backup
version: 1.2
author:
  - Aaron Straup Cope E<lt>ascope@cpan.orgE<gt>
abstract: OOP for backing up your Flickr photos locally
license: perl
requires:
  Config::Simple: 0
  Date::Format: >= 2.22
  Date::Parse: >= 2.27
  Encode: >= 2.09
  File::Find::Rule: 0
  Flickr::API: >= 0.07
  IO::AtomicFile: >= 2.101
  LWP::Simple: >= 1.38
  Log::Dispatch: >= 2.10
  RDF::Simple: >= 0.21
  Text::Unidecode: >= 0.04
  XML::XPath: >= 1.13
  perl: >= 5.8.0
build_requires:
  Test::Simple: >= 0.47
provides:
  Net::Flickr::Backup:
    file: lib/Net/Flickr/Backup.pm
    version: 1.2
generated_by: Module::Build version 0.2611
