--- #YAML:1.0
name: Net-Flickr-Backup
version: 2.93
author:
  - Aaron Straup Cope E<lt>ascope@cpan.orgE<gt>
abstract: OOP for backing up your Flickr photos locally
license: perl
generated_by: Module::Build version 0.2611, without YAML.pm
